"""Add is_paid column

Revision ID: 498cc3ec72a5
Revises: 85a6df44e598
Create Date: 2025-11-23 01:34:00.318816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498cc3ec72a5'
down_revision = '85a6df44e598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
