"""Add payment_method to Order model

Revision ID: 74814cb60bd5
Revises: 5530adfa1a9f
Create Date: 2025-11-11 19:04:32.996973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74814cb60bd5'
down_revision = '5530adfa1a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
