"""Add shipping fee

Revision ID: 85a6df44e598
Revises: 0d7533b9f2dd
Create Date: 2025-11-21 15:33:54.985243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a6df44e598'
down_revision = '0d7533b9f2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('shipping_fee')

    # ### end Alembic commands ###
