"""Add HealthScreening model

Revision ID: fad62eb8cb40
Revises: 498cc3ec72a5
Create Date: 2025-11-24 00:59:21.598541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad62eb8cb40'
down_revision = '498cc3ec72a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('q1', sa.Boolean(), nullable=True),
    sa.Column('q2', sa.Boolean(), nullable=True),
    sa.Column('q3', sa.Boolean(), nullable=True),
    sa.Column('q4', sa.Boolean(), nullable=True),
    sa.Column('q5', sa.Boolean(), nullable=True),
    sa.Column('q6', sa.Boolean(), nullable=True),
    sa.Column('q7', sa.Boolean(), nullable=True),
    sa.Column('risk_detected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_screenings')
    # ### end Alembic commands ###
